# Linux (musl) targets
[target.x86_64-unknown-linux-musl]
linker = "zig cc -target x86_64-linux-musl"

[target.aarch64-unknown-linux-musl]
linker = "zig cc -target aarch64-linux-musl"

[target.armv7-unknown-linux-musleabihf]
linker = "zig cc -target arm-linux-musleabihf"
